name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## National Rail UK Home Assistant Component
            
            ### What's New
            - National Rail UK integration for Home Assistant
            - Lovelace card for displaying train departures
            - Support for the new Rail Data API
            
            ### Installation
            Install via HACS or manually following the README instructions.
          draft: false
          prerelease: false 